version: '3.8'

services:
  db:
    container_name: votes_db
    image: mysql:5.7
    ports:
      - '3307:3306'
    volumes:
      - votes_db:/var/lib/mysql
    extends:
      file: ./docker/mysql/password.yml
      service: password

  web:
    container_name: votes_app
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    command: bash -c "bundle install && rails server -b 0.0.0.0"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  votes_db: